# Generated by Django 4.2.1 on 2023-06-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myevent', '0003_eventcategory_eventsubcategory_eventtype_newevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newevent',
            name='is_cutoff_time',
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='is_ticket_sale_immediate',
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='is_ticket_sale_schedule',
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='ticket_sale_end_time',
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='maximum_ticket_order',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='minimum_ticket_order',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_buy_by_list',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_password',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AlterField(
            model_name='newevent',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
